package ventanas;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.DateField;
import com.vaadin.ui.PasswordField;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Anadir_datos_usuario_ventanas extends VerticalLayout {
	protected TextField nombre;
	protected TextField apellidos;
	protected TextField apodo;
	protected TextField correo;
	protected PasswordField contrasena;
	protected PasswordField repContrasena;
	protected DateField fechaNacimiento;
	protected TextField urlPhoto;

	public Anadir_datos_usuario_ventanas() {
		Design.read(this);
	}
}
