package ventanas;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.FormLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Crear_categoria_ventanas extends VerticalLayout {
	protected Label crear_categoria_label;
	protected TextField nombre_categoria;
	protected TextField edad_permitida;
	protected Button atras;
	protected Button crear_categoria_button;
	protected VerticalLayout vetical;
	protected FormLayout formLayout;

	public Crear_categoria_ventanas() {
		Design.read(this);
	}
}
