package ventanas;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Ficha_video_ventanas extends VerticalLayout {
	protected Panel panelVideo;
	protected HorizontalLayout layoutReproductor;
	protected HorizontalLayout losMegustas;
	protected Label titulo_video;
	protected Label nVisualizacion;
	protected Label nMegusta;
	protected Panel panelDescripcion;
	protected Button nombre_usuario;
	protected Label fecha_subida;
	protected Label descripcion_video;
	protected Label categoria;
	protected Label etiquetas;
	protected Label enlace;

	public Ficha_video_ventanas() {
		Design.read(this);
	}
}
