package ventanas;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.FormLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.TextField;
import com.vaadin.ui.declarative.Design;
import ventanas.Video_subido_ventanas;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Lista_videos_subidos_ventanas extends Panel {
	protected Label titulo;
	protected TextField buscadorTF;
	protected Button buscarB;
	protected FormLayout listaVideosFL;
	protected Video_subido_ventanas video_subido;

	public Lista_videos_subidos_ventanas() {
		Design.read(this);
	}
}
