package ventanas;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.FormLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Listas_de_reproduccion_ventanas extends VerticalLayout {
	protected Label titulo_listas_de_reproducion;
	protected VerticalLayout vertical;
	protected HorizontalLayout horizontal;
	protected FormLayout form;
	protected Button lista12;
	protected Label lista1;
	protected Button lista121;
	protected Label lista11;
	protected Button lista122;
	protected Label lista13;

	public Listas_de_reproduccion_ventanas() {
		Design.read(this);
	}
}
