package ventanas;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Image;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;
import ventanas.Zona_cabecera_administrador_ventanas;
import ventanas.Zona_opciones_administrador_ventanas;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Perfil_administrador_ventanas extends VerticalLayout {
	protected Image logo;
	protected VerticalLayout vertical;
	protected Zona_cabecera_administrador_ventanas zcav;
	protected Zona_opciones_administrador_ventanas zoav;

	public Perfil_administrador_ventanas() {
		Design.read(this);
	}
}
