package ventanas;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;
import ventanas.Zona_cabecera_perfli_Registrado_ventanas;
import ventanas.Zona_cuerpo_perfil_registrado_ventanas;
import ventanas.Zona_opciones_perfil_registrado_ventanas;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Perfil_registrado_ventanas extends Panel {
	protected VerticalLayout vertical;
	protected Zona_cabecera_perfli_Registrado_ventanas cabecera;
	protected HorizontalLayout horizontal;
	protected Zona_opciones_perfil_registrado_ventanas zona_opciones_perfil_registrado;
	protected Zona_cuerpo_perfil_registrado_ventanas zona_cuerpo_perfil_registrado;

	public Perfil_registrado_ventanas() {
		Design.read(this);
	}
}
