package ventanas;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;
import ventanas.Anadir_datos_video_ventanas;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Subir_video_ventanas extends VerticalLayout {
	protected Label titulo_subir_nuevo_video;
	protected Anadir_datos_video_ventanas anadirDatosVideo;
	protected Button atras;
	protected Button subir_video;

	public Subir_video_ventanas() {
		Design.read(this);
	}
}
