package ventanas;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;
import ventanas.Zona_inicio_cabecera_registrado_ventanas;
import ventanas.Zona_inicio_cuerpo_registrado_ventanas;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Usuario_registrado_ventanas extends Panel {
	protected VerticalLayout vertical;
	protected Zona_inicio_cabecera_registrado_ventanas zicr;
	protected Zona_inicio_cuerpo_registrado_ventanas zicr1;

	public Usuario_registrado_ventanas() {
		Design.read(this);
	}
}
