package ventanas;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;
import ventanas.Lista_videos_subidos_ventanas;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Zona_cuerpo_perfil_registrado_ventanas extends VerticalLayout {
	protected HorizontalLayout cuerpo_regitrado;
	protected Panel panelVideosPropios;
	protected VerticalLayout verticalVideos;
	protected Lista_videos_subidos_ventanas lv;
	protected Panel panelListaReproduccion;
	protected VerticalLayout verticalListas;

	public Zona_cuerpo_perfil_registrado_ventanas() {
		Design.read(this);
	}
}
