package ventanas;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.FormLayout;
import com.vaadin.ui.NativeSelect;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Zona_opciones_video_propietario_ventanas extends VerticalLayout {
	protected FormLayout form;
	protected Button me_gusta;
	protected Button descargar;
	protected Button crear_lista_reproduccion;
	protected NativeSelect<java.lang.String> anadirLista;
	protected Button eliminar;

	public Zona_opciones_video_propietario_ventanas() {
		Design.read(this);
	}
}
