package ventanas;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.Image;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Zona_cabecera_comun_ventanas extends VerticalLayout {
	protected Image logo;
	protected Label nVisitas;
	protected Label nSuscriptores;
	protected Button ver_listado_suscriptores;
	protected Label nSuscripciones;
	protected Button ver_listado_suscripciones;
	protected Image imagen;

	public Zona_cabecera_comun_ventanas() {
		Design.read(this);
	}
}
