package ventanas;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Zona_inicio_cabecera_registrado_ventanas extends HorizontalLayout {
	protected HorizontalLayout iniciar_sesion_layout;
	protected Button mi_perfil;
	protected Button cerrar_sesion;

	public Zona_inicio_cabecera_registrado_ventanas() {
		Design.read(this);
	}
}
